### PR TITLE
Simplified TileDBArray getters to use tiledb_array.

### LINKED ISSUE #9: Thoughts on using tiledb_array
Having played around with `tiledb_array` on 0.7.0, here are some thoughts on its integration with `TileDBArray`. I will use the following example to provide some context:

```r
library(tiledb)
tmp <- tempfile()
dir.create(tmp)

d1  <- tiledb_dim("d1", domain = c(1L, 5L))
d2  <- tiledb_dim("d2", domain = c(1L, 5L))
dom <- tiledb_domain(c(d1, d2))
val <- tiledb_attr("val", type = "FLOAT64")
sch <- tiledb_array_schema(dom, c(val))
tiledb_array_create(tmp, sch)

A <- tiledb_array(uri = tmp)
A[] <- data.frame(d1=rep(1:5,5), d2=rep(1:5,each=5), val=1:25)
```

## Error when the index is a symbol

There's some odd `substitute()` calls inside the `[` method that probably causes this:

```r
A[list(c(1,2), c(4,5)),] 
## $d1
##  [1] 1 1 1 1 1 2 2 2 2 2 4 4 4 4 4 5 5 5 5 5
## 
## $d2
##  [1] 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5
## 
## $val
##  [1]  1  6 11 16 21  2  7 12 17 22  4  9 14 19 24  5 10 15 20 25

Y <- list(c(1,2), c(4,5))
A[Y,]
## Error in is[[1]] : object of type 'symbol' is not subsettable
```

This blocks programmatic usage for the time being.

## Preferred subset output

In fact, it doesn't even have to be the `[` function, you could give me an entirely different function that does this. Let's call it `tiledb_extract_indices()` for now. For the inputs, I would like:

- the `tiledb_array` object `x`, let's say with N dimensions.
- one or more indexing arguments, say `i` for the first dimension, `j` and so on. These would be integer vectors (or `NULL`, if we want all of that dimension).

For outputs, I would like a N-column matrix of coordinates and a vector - or `data.frame`, I suppose, to handle multiple attributes - of values. The matrix and the `data.frame` have the same number of rows but are separated to make it easier to distinguish between location and value.

The coordinates themselves would refer to the coordinates of the indexing arguments `i` and `j` and friends, not the coordinates on the full array in `x`. This is important as it disambiguates between duplicated values in `i`. For example, I would like to be able to do this:

```r
# (Ideally, d1 and d2 would be their own matrix or df so that it is easy
# to understand which elements are indices and which are values.
# Nonetheless, I'll show it like this to make it easier to compare with 
# the current state of affairs.)
tiledb_extract_indices(x, i=c(2,2,2,2), j=1)
## $d1
##  [1] 1 2 3 4
##
## $d2
##  [1] 1 1 1 1
##
## $val
##  [1] 2 2 2 2
``` 

From this output, I can easily construct an array or sparse matrix with rows defined by `i` and columns defined by `j`. If I need the full indices (with respect to the entire array), I can simply subset `i` by `d1` and `j` by `d2`. just  In contrast, the current behavior is to do:

```r
A[list(2,2,2,2),list(1)]
## $d1
## [1] 2 2 2 2
## 
## $d2
## [1] 1 1 1 1
## 
## $val
## [1] 2 2 2 2
```

This is harder to reason with because I now need to figure out which of the 2's in `d1` match up with the 2's in the row-subsetting list `i`.
 
Similarly, `tiledb_extract_indices` would be in charge of figuring out how to create a query from arbitrary integer vectors in `i` and `j` and friends. The current state requires me to perform a series of loops to arrange the inputs in the right manner (namely to identify continguous runs and create a list with one entry for the run's start and endpoints), which is unlikely to be efficient.

### PR DESCRIPTION
**Pull request by LTLA**
Closes #9.

### CODE REVIEW

**Comment by eddelbuettel** [comment]
I added some minor polishing so that the package tests once again in Travis---and also updated the underlying Docker container to use the feature/select_ranges branch we currently need.  So it now once again passes for me:

```sh
edd@rob:~/git/tiledbarray(simplified)$ docker run --rm -ti -v $(pwd):/mnt -w /mnt eddelbuettel/rocker-tiledb:bioc R CMD check --no-vignettes --no-manual TileDBArray_0.0.1.1.tar.gz
* using log directory ‘/mnt/TileDBArray.Rcheck’
* using R version 4.0.1 (2020-06-06)                                                                     
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* using options ‘--no-manual --no-vignettes’
* checking for file ‘TileDBArray/DESCRIPTION’ ... OK                                                     
* this is package ‘TileDBArray’ version ‘0.0.1.1’                                                        
* package encoding: UTF-8  
* checking package namespace information ... OK                                                          
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK           
* checking for .dll and .exe files ... OK                                                                
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘TileDBArray’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK  
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking line endings in C/C++/Fortran sources/headers ... OK
* checking compiled code ... OK
* checking files in ‘vignettes’ ... WARNING
Files in the 'vignettes' directory but no files in 'inst/doc':
  ‘userguide.Rmd’
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ...
  Running ‘testthat.R’
 OK
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... WARNING
dir.exists(dir) is not TRUE
Package vignette without corresponding single PDF/HTML:
   ‘userguide.Rmd’

* checking running R code from vignettes ... SKIPPED
* checking re-building of vignette outputs ... SKIPPED
* DONE

Status: 2 WARNINGs
See
  ‘/mnt/TileDBArray.Rcheck/00check.log’
for details.


edd@rob:~/git/tiledbarray(simplified)$ 
```

(I often locally increment the version which is why this uses 0.0.1.1, I have not committed that change to `DESCRIPTION`.)

But it looks like Travis may be turned off right now.  Feel free to turn it back and test.  It should pass.

**Comment by eddelbuettel** [comment]
> But it looks like Travis may be turned off right now. Feel free to turn it back and test. It should pass.

I don't understand what is happening here. I did some work on two other repos and they ran Travis fine as commits were made.

**Comment by LTLA** [comment]
Seems like there was a transient docker pull issue on Travis, I just refired it and it looked fine.

Is the `--no-vignette-build` desired? ~Looks like it's triggering CHECK warnings again.~ Looks fine, actually.

**Comment by LTLA** [comment]
Hm. Looks like I was too trigger-happy there, Travis is now seeing those "could not parse" errors again. 

I'll try a few things in a separate PR.

**Comment by eddelbuettel** [comment]
We can chat on Slack for more detail, but yes -- at least for now -- the `--no-build-vignettes` is needed as the container does NOT contain `pandoc`.  It is trivial to add that.

**Pull request merged**
